/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodj_assignment;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
/**
 *
 * @author asus
 */
public class Admin_User_Menu extends javax.swing.JFrame {

    String addRole = null;
    String searchRole = null;
    String viewRole = null;
    AdminUser admin = new AdminUser();
    String filePath = "User.txt";

    private Admin_User_Menu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    enum Role
    {
        Admin,
        Customer
    }
            
    UserLogin loginUser = new UserLogin();
    
    DefaultListModel lm = new DefaultListModel(); //Listbox model(contents)
    public Admin_User_Menu(UserLogin login) {
        initComponents();
        setSize(1000, 650);//Width and Height
        setResizable(false);
        lblRole.setText(login.getRole());
        lblId.setText(login.getId());
        lblUsername.setText(login.getUsername());
        loginUser=login;

        lm.removeAllElements();

        //Control set to false
        btnUserMenu.setEnabled(false);
        btnSignUp.setEnabled(false);
        btnView.setEnabled(false);
        btnSearch.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        rdoEditUsername.setEnabled(false);
        rdoEditPassword.setEnabled(false);
        txtEditUsername.setEnabled(false);
        txtEditPassword.setEnabled(false);
        
        lstView.setModel(lm); //Attached to the listbox
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsername2 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblPConfirmPassword = new javax.swing.JLabel();
        lblrole = new javax.swing.JLabel();
        txtAddUsername = new javax.swing.JTextField();
        txtAddPassword = new javax.swing.JTextField();
        txtConfirmPassword = new javax.swing.JTextField();
        rdoAdmin = new javax.swing.JRadioButton();
        rdoCust = new javax.swing.JRadioButton();
        btnSignUp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstView = new javax.swing.JList<>();
        btnView = new javax.swing.JButton();
        rdoViewCust = new javax.swing.JRadioButton();
        rdoViewAdmin = new javax.swing.JRadioButton();
        btnLogfile = new javax.swing.JButton();
        lblUsername3 = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblRole1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblID1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblUsername1 = new javax.swing.JLabel();
        txtSearchUsername = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtEditUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdoEditUsername = new javax.swing.JRadioButton();
        rdoEditPassword = new javax.swing.JRadioButton();
        rdoSearchAdmin = new javax.swing.JRadioButton();
        rdoSearchCust = new javax.swing.JRadioButton();
        txtEditPassword = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnUserMenu = new javax.swing.JButton();
        btnProductMenu = new javax.swing.JButton();
        btnOrderItemMenu = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnOrderMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setPreferredSize(new java.awt.Dimension(950, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 650));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Sign Up");

        lblUsername2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername2.setText("Username:");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setText("Password:");

        lblPConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPConfirmPassword.setText("Confirm Password:");

        lblrole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblrole.setText("Role:");

        txtAddUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAddUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtAddUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddUsernameKeyPressed(evt);
            }
        });

        txtAddPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAddPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtAddPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddPasswordKeyPressed(evt);
            }
        });

        txtConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtConfirmPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConfirmPasswordKeyPressed(evt);
            }
        });

        buttonGroup1.add(rdoAdmin);
        rdoAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoAdmin.setText("Admin");
        rdoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAdminActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoCust);
        rdoCust.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoCust.setText("Customer");
        rdoCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCustActionPerformed(evt);
            }
        });

        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblrole)
                            .addComponent(lblPConfirmPassword)
                            .addComponent(lblPassword)
                            .addComponent(lblUsername2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rdoAdmin)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdoCust))
                                .addComponent(txtAddPassword)
                                .addComponent(txtAddUsername)
                                .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblUsername2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPConfirmPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblrole))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtAddUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAddPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoAdmin)
                            .addComponent(rdoCust))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSignUp)))
                .addContainerGap())
        );

        lstView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(lstView);

        btnView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnView.setText("View All Users");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoViewCust);
        rdoViewCust.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoViewCust.setText("Customer");
        rdoViewCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoViewCustActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoViewAdmin);
        rdoViewAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoViewAdmin.setText("Admin");
        rdoViewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoViewAdminActionPerformed(evt);
            }
        });

        btnLogfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogfile.setText("View Logfile");
        btnLogfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogfileActionPerformed(evt);
            }
        });

        lblUsername3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername3.setText("Role:");

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRole.setText("Role");

        lblRole1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRole1.setText("ID:");

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblId.setText("ID");

        lblID1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblID1.setText("Username:");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setText("Username");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoViewAdmin)
                .addGap(18, 18, 18)
                .addComponent(rdoViewCust)
                .addGap(118, 118, 118))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogfile, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUsername3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRole)
                        .addGap(18, 18, 18)
                        .addComponent(lblRole1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblId)
                        .addGap(18, 18, 18)
                        .addComponent(lblID1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsername)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername3)
                    .addComponent(lblRole)
                    .addComponent(lblRole1)
                    .addComponent(lblId)
                    .addComponent(lblID1)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoViewAdmin)
                    .addComponent(rdoViewCust))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnLogfile))
                .addGap(12, 12, 12))
        );

        lblUsername1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername1.setText("Username:");

        txtSearchUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtSearchUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchUsernameKeyPressed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtEditUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtEditUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEditUsernameKeyPressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Edit");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Search");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Delete");

        rdoEditUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoEditUsername.setText("Username:");
        rdoEditUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoEditUsernameActionPerformed(evt);
            }
        });

        rdoEditPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoEditPassword.setText("Password:");
        rdoEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoEditPasswordActionPerformed(evt);
            }
        });

        buttonGroup3.add(rdoSearchAdmin);
        rdoSearchAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoSearchAdmin.setText("Admin");
        rdoSearchAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSearchAdminActionPerformed(evt);
            }
        });

        buttonGroup3.add(rdoSearchCust);
        rdoSearchCust.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoSearchCust.setText("Customer");
        rdoSearchCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSearchCustActionPerformed(evt);
            }
        });

        txtEditPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtEditPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEditPasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoEditUsername)
                            .addComponent(rdoEditPassword))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEditUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(txtEditPassword)))
                    .addComponent(jLabel3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(20, 20, 20)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblUsername1)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rdoSearchAdmin)
                        .addGap(18, 18, 18)
                        .addComponent(rdoSearchCust)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoSearchAdmin)
                    .addComponent(rdoSearchCust))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername1)
                    .addComponent(txtSearchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEditUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoEditUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoEditPassword)
                    .addComponent(txtEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addContainerGap())
        );

        btnUserMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUserMenu.setText("User Menu");
        btnUserMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserMenuActionPerformed(evt);
            }
        });

        btnProductMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProductMenu.setText("Product Menu");
        btnProductMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductMenuActionPerformed(evt);
            }
        });

        btnOrderItemMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrderItemMenu.setText("Order Items Menu");
        btnOrderItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderItemMenuActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnOrderMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrderMenu.setText("Order Menu");
        btnOrderMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUserMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProductMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrderMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrderItemMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProductMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrderItemMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrderMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUserMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserMenuActionPerformed

    private void btnProductMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductMenuActionPerformed
        this.dispose();
        Admin_Product_Menu productMenu = new Admin_Product_Menu(loginUser);
        productMenu.setVisible(true);
    }//GEN-LAST:event_btnProductMenuActionPerformed

    private void btnOrderItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderItemMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderItemMenuActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnOrderMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderMenuActionPerformed
        
    }//GEN-LAST:event_btnOrderMenuActionPerformed

    private void txtEditPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditPasswordKeyPressed
        char c = evt.getKeyChar();

        if (Character.isSpaceChar(c))
        {
            txtEditPassword.setEditable(false);
        }
        else
        {
            txtEditPassword.setEditable(true);
        }
    }//GEN-LAST:event_txtEditPasswordKeyPressed

    private void rdoSearchCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSearchCustActionPerformed
        Role role = Role.Customer;
        searchRole = role.toString();
        btnSearch.setEnabled(true);
    }//GEN-LAST:event_rdoSearchCustActionPerformed

    private void rdoSearchAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSearchAdminActionPerformed
        Role role = Role.Admin;
        searchRole = role.toString();
        btnSearch.setEnabled(true);
    }//GEN-LAST:event_rdoSearchAdminActionPerformed

    private void rdoEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoEditPasswordActionPerformed
        if (rdoEditUsername.isSelected() || rdoEditPassword.isSelected())
        {
            btnEdit.setEnabled(true);
        }
        else
        {
            btnEdit.setEnabled(false);
        }

        if (rdoEditUsername.isSelected())
        {
            txtEditUsername.setEnabled(true);
        }
        else
        {
            txtEditUsername.setEnabled(false);
        }

        if (rdoEditPassword.isSelected())
        {
            txtEditPassword.setEnabled(true);
        }
        else
        {
            txtEditPassword.setEnabled(false);
        }
    }//GEN-LAST:event_rdoEditPasswordActionPerformed

    private void rdoEditUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoEditUsernameActionPerformed
        if (rdoEditUsername.isSelected() || rdoEditPassword.isSelected())
        {
            btnEdit.setEnabled(true);
        }
        else
        {
            btnEdit.setEnabled(false);
        }

        if (rdoEditUsername.isSelected())
        {
            txtEditUsername.setEnabled(true);
        }
        else
        {
            txtEditUsername.setEnabled(false);
        }

        if (rdoEditPassword.isSelected())
        {
            txtEditPassword.setEnabled(true);
        }
        else
        {
            txtEditPassword.setEnabled(false);
        }

    }//GEN-LAST:event_rdoEditUsernameActionPerformed

    private void txtEditUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditUsernameKeyPressed
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isDigit(c) || Character.isISOControl(c) || c==95)
        {
            txtEditUsername.setEditable(true);
        }
        else
        {
            txtEditUsername.setEditable(false);
        }
    }//GEN-LAST:event_txtEditUsernameKeyPressed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            admin.deleteOneUser(searchRole, txtSearchUsername.getText());
        } catch (IOException ex) {
            Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "User successfully deleted!");
        txtSearchUsername.setText(null);
        buttonGroup3.clearSelection();
        rdoEditUsername.setEnabled(false);
        rdoEditPassword.setEnabled(false);
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        User user = new User();
        String[] title = {"Role", "ID", "Username", "Password"};
        String[] searchResult = null;
        boolean print = false;
        if (!txtEditUsername.getText().isBlank() && !txtEditPassword.getText().isBlank() && rdoEditUsername.isSelected() && rdoEditPassword.isSelected())
        {
            //Both change
            try {
                if (user.checkUserExist(filePath, searchRole, txtEditUsername.getText()))
                {
                    JOptionPane.showMessageDialog(this, "User exist! Please try again");
                }
                else
                {
                    try {
                        admin.editOneUser(searchRole, txtSearchUsername.getText(), txtEditUsername.getText(), txtEditPassword.getText());
                    } catch (IOException ex) {
                        Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    print = true;
                }
            } catch (IOException ex) {
                Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (!txtEditUsername.getText().isBlank() && !rdoEditPassword.isSelected())
        {
            //Change username
            try {
                if (user.checkUserExist(filePath, searchRole, txtEditUsername.getText()))
                {
                    JOptionPane.showMessageDialog(this, "User exist! Please try again");
                }
                else
                {
                    try {
                        admin.editOneUser(searchRole, txtSearchUsername.getText(), txtEditUsername.getText());
                    } catch (IOException ex) {
                        Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    print = true;
                }
            } catch (IOException ex) {
                Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (!txtEditPassword.getText().isBlank() && !rdoEditUsername.isSelected())
        {
            //Change password
            try {
                admin.editOneUser(searchRole, txtSearchUsername.getText(), txtSearchUsername.getText(), txtEditPassword.getText());
            } catch (IOException ex) {
                Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            print = true;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid input! Please try again!");
        }

        if (print == true)
        {
            lm.addElement("\n");
            lm.addElement("<html><b>After Edit:<html><b>");
            if (!rdoEditUsername.isSelected())
            {

                try {
                    searchResult = admin.searchOneUser(searchRole, txtSearchUsername.getText());
                } catch (IOException ex) {
                    Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
                for (int i=0; i<title.length;i++)
                {
                    lm.addElement(title[i] + ": " + searchResult[i]);
                }
            }
            else
            {
                try {
                    searchResult = admin.searchOneUser(searchRole, txtEditUsername.getText());
                } catch (IOException ex) {
                    Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
                for (int i=0; i<title.length;i++)
                {
                    lm.addElement(title[i] + ": " + searchResult[i]);
                }
            }
        }
        txtEditUsername.setText(null);
        txtEditUsername.setEnabled(false);
        txtEditPassword.setText(null);
        txtEditPassword.setEnabled(false);
        txtSearchUsername.setText(null);
        rdoEditUsername.setSelected(false);
        rdoEditPassword.setSelected(false);
        rdoEditUsername.setEnabled(false);
        rdoEditPassword.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchResult[] = null;
        String[] title = {"Role", "ID", "Username", "Password"};
        lm.removeAllElements();

        try {
            searchResult = admin.searchOneUser(searchRole, txtSearchUsername.getText());
        } catch (IOException ex) {
            Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (searchResult[2]==null)
        {
            lm.addElement("<html><b>User Not Found!<html><b>");
            rdoEditUsername.setEnabled(false);
            rdoEditPassword.setEnabled(false);
            btnDelete.setEnabled(false);
            txtSearchUsername.setText(null);
            btnSearch.setEnabled(false);
            buttonGroup3.clearSelection();
        }
        else
        {
            lm.addElement("<html><b>Search Result:<html><b>");
            for (int i=0; i<title.length;i++)
            {
                lm.addElement(title[i] + ": " + searchResult[i]);
            }
            rdoEditUsername.setEnabled(true);
            rdoEditPassword.setEnabled(true);
            btnDelete.setEnabled(true);
            buttonGroup3.clearSelection();
            btnSearch.setEnabled(false);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchUsernameKeyPressed
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isDigit(c) || Character.isISOControl(c) || c==95)
        {
            txtSearchUsername.setEditable(true);
        }
        else
        {
            txtSearchUsername.setEditable(false);
        }
    }//GEN-LAST:event_txtSearchUsernameKeyPressed

    private void btnLogfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogfileActionPerformed
        lm.removeAllElements();
        lm.addElement("<html><b>User Login Logfile:<html><b>");
        UserLogin login = new UserLogin();
        String[][] userLog = null;
        try {
            userLog = login.viewLogfile();
        } catch (IOException ex) {
            Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < userLog.length; i++)
        {
            if (userLog[i][0]!=null)
            {
                lm.addElement(userLog[i][0] + " : " + userLog[i][1] + " : " + userLog[i][2] + " : " + userLog[i][3] + " : " + userLog[i][4]);
            }
        }
    }//GEN-LAST:event_btnLogfileActionPerformed

    private void rdoViewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoViewAdminActionPerformed
        Role role = Role.Admin;
        viewRole = role.toString();
        btnView.setEnabled(true);
    }//GEN-LAST:event_rdoViewAdminActionPerformed

    private void rdoViewCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoViewCustActionPerformed
        Role role = Role.Customer;
        viewRole = role.toString();
        btnView.setEnabled(true);
    }//GEN-LAST:event_rdoViewCustActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        lm.removeAllElements();
        lm.addElement("<html><b>"+viewRole+"<html><b>");
        String[] title = {"Role", "ID", "Username", "Password"};
        String[][] userList = null;
        try {
            userList = admin.viewAllUser(viewRole);
        } catch (IOException ex) {
            Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < userList.length; i++)
        {
            if (userList[i]!=null)
            {
                if (userList[i][0]!=null)
                {
                    lm.addElement(title[0] + ": " + userList[i][0]);
                    lm.addElement(title[1] + ": " + userList[i][1]);
                    lm.addElement(title[2] + ": " + userList[i][2]);
                    lm.addElement(title[3] + ": " + userList[i][3]);
                    lm.addElement("\n");
                }
            }
        }
        lm.addElement("\n");
        buttonGroup2.clearSelection();
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        lm.removeAllElements();
        String searchResult[] = null;
        String[] title = {"Role", "ID", "Username", "Password"};
        if (!txtAddUsername.getText().isBlank() && !txtAddPassword.getText().isBlank())
        {
            try {
                if (admin.checkUserExist(filePath, addRole, txtAddUsername.getText()))
                {
                    JOptionPane.showMessageDialog(this, "User exist! Please try again");
                }
                else
                {
                    admin.setNewUsername(txtAddUsername.getText());
                    if (txtAddPassword.getText().equals(txtConfirmPassword.getText()))
                    {
                        admin.setNewPassword(txtAddPassword.getText());
                        admin.addNewUser(addRole);
                        try {
                            searchResult = admin.searchOneUser(addRole, txtAddUsername.getText());
                        } catch (IOException ex) {
                            Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        lm.addElement("<html><b>New User:<html><b>");
                        for (int i=0; i<title.length;i++)
                        {
                            lm.addElement(title[i] + ": " + searchResult[i]);
                        }
                        JOptionPane.showMessageDialog(this, "User successfully added!");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Two password are not match!");
                    }

                }
            } catch (IOException ex) {
                Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid input! Please try again");

        }
        buttonGroup1.clearSelection();
        btnSignUp.setEnabled(false);
        txtAddUsername.setText(null);
        txtAddPassword.setText(null);
        txtConfirmPassword.setText(null);
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void rdoCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCustActionPerformed
        Role role = Role.Customer;
        addRole = role.toString();
        btnSignUp.setEnabled(true);
    }//GEN-LAST:event_rdoCustActionPerformed

    private void rdoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAdminActionPerformed
        Role role = Role.Admin;
        addRole = role.toString();
        btnSignUp.setEnabled(true);
    }//GEN-LAST:event_rdoAdminActionPerformed

    private void txtConfirmPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmPasswordKeyPressed
        char c = evt.getKeyChar();

        if (Character.isSpaceChar(c))
        {
            txtConfirmPassword.setEditable(false);
        }
        else
        {
            txtConfirmPassword.setEditable(true);
        }
    }//GEN-LAST:event_txtConfirmPasswordKeyPressed

    private void txtAddPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddPasswordKeyPressed
        char c = evt.getKeyChar();

        if (Character.isSpaceChar(c))
        {
            txtAddPassword.setEditable(false);
        }
        else
        {
            txtAddPassword.setEditable(true);
        }
    }//GEN-LAST:event_txtAddPasswordKeyPressed

    private void txtAddUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddUsernameKeyPressed
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isDigit(c) || Character.isISOControl(c) || c==95)
        {
            txtAddUsername.setEditable(true);
        }
        else
        {
            txtAddUsername.setEditable(false);
        }
    }//GEN-LAST:event_txtAddUsernameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_User_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_User_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_User_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_User_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_User_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogfile;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrderItemMenu;
    private javax.swing.JButton btnOrderMenu;
    private javax.swing.JButton btnProductMenu;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton btnUserMenu;
    private javax.swing.JButton btnView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPConfirmPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRole1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel lblUsername2;
    private javax.swing.JLabel lblUsername3;
    private javax.swing.JLabel lblrole;
    private javax.swing.JList<String> lstView;
    private javax.swing.JRadioButton rdoAdmin;
    private javax.swing.JRadioButton rdoCust;
    private javax.swing.JRadioButton rdoEditPassword;
    private javax.swing.JRadioButton rdoEditUsername;
    private javax.swing.JRadioButton rdoSearchAdmin;
    private javax.swing.JRadioButton rdoSearchCust;
    private javax.swing.JRadioButton rdoViewAdmin;
    private javax.swing.JRadioButton rdoViewCust;
    private javax.swing.JTextField txtAddPassword;
    private javax.swing.JTextField txtAddUsername;
    private javax.swing.JTextField txtConfirmPassword;
    private javax.swing.JTextField txtEditPassword;
    private javax.swing.JTextField txtEditUsername;
    private javax.swing.JTextField txtSearchUsername;
    // End of variables declaration//GEN-END:variables
}
