/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodj_assignment;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
/**
 *
 * @author asus
 */
public class Admin_OrderSearchView_Menu extends javax.swing.JFrame {

    String newType = null;
    String editType = null;
    String viewType = null;
    Order order = new Order();
    AdminUser admin;


    Admin_OrderSearchView_Menu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    DefaultListModel lm = new DefaultListModel(); //Listbox model(contents)
    public Admin_OrderSearchView_Menu(AdminUser admin) {
        this.admin = admin;
        initComponents();
        setSize(950, 650);//Width and Height
        setResizable(false);
        btnOrderSearchView.setEnabled(false);
        lm.removeAllElements();
        
        //Control set to false
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnViewOrder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstView = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        lblOrderProduct = new javax.swing.JLabel();
        txtSearchOrder = new javax.swing.JTextField();
        btnSearchOrder = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnUser = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnOrderSearchView = new javax.swing.JButton();
        btnAddOrder = new javax.swing.JButton();
        btnOrderEditDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search/View Order");
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 650));

        btnViewOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewOrder.setText("View All Orders");
        btnViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderActionPerformed(evt);
            }
        });

        lstView.setColumns(20);
        lstView.setRows(5);
        jScrollPane2.setViewportView(lstView);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewOrder)
                .addGap(128, 128, 128))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewOrder)
                .addGap(12, 12, 12))
        );

        lblOrderProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrderProduct.setText("Name:");

        txtSearchOrder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtSearchOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchOrderKeyPressed(evt);
            }
        });

        btnSearchOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchOrder.setText("Search");
        btnSearchOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchOrderActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Search order product");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblOrderProduct)
                        .addGap(28, 28, 28)
                        .addComponent(txtSearchOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderProduct)
                    .addComponent(txtSearchOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchOrder))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUser.setText("User menu");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        btnProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProduct.setText("Product menu");
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnOrderSearchView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrderSearchView.setText("Search/View Order");
        btnOrderSearchView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderSearchViewActionPerformed(evt);
            }
        });

        btnAddOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddOrder.setText("Add Order");
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderActionPerformed(evt);
            }
        });

        btnOrderEditDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrderEditDelete.setText("Edit/Delete Order");
        btnOrderEditDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderEditDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnUser)
                .addGap(18, 18, 18)
                .addComponent(btnProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnAddOrder)
                .addGap(26, 26, 26)
                .addComponent(btnOrderEditDelete)
                .addGap(18, 18, 18)
                .addComponent(btnOrderSearchView)
                .addGap(33, 33, 33)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrderSearchView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrderEditDelete)
                    .addComponent(btnAddOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProduct)
                    .addComponent(btnUser))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 418, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        UserLogin logout = new UserLogin();
        logout.getAndWriteLogfile("Logout", admin.getRole(), admin.getId(), admin.getUsername(), admin.getPassword());
        this.dispose();
        Login mainLogin = new Login();
        mainLogin.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnOrderEditDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderEditDeleteActionPerformed
        this.dispose();
        Admin_OrderEditDelete_Menu menu = new Admin_OrderEditDelete_Menu(admin);
        menu.setVisible(true);
    }//GEN-LAST:event_btnOrderEditDeleteActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        this.dispose();
        Admin_Product_Menu productmenu = new Admin_Product_Menu(admin);
        productmenu.setVisible(true);
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        this.dispose();
        Admin_User_Menu usermenu = new Admin_User_Menu(admin);
        usermenu.setVisible(true);
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnSearchOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchOrderActionPerformed
        String searchResult[] = null;
        lstView.removeAll();

        String[] title = {"Customer Name","Name", "Quantity", "Price", "Total"};
        int x=0;
        try {
            searchResult = order.searchAllOrderName(txtSearchOrder.getText());
        } catch (IOException ex) {
            Logger.getLogger(Admin_OrderSearchView_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (searchResult[0]==null)
        {
            lstView.setText("Order Not Found!");
            txtSearchOrder.setText(null);
        }
        else
        {
            lstView.setText("Search Result: "+"\n");
            for (int i=0; i<searchResult.length;i++)
            {

                if(i%5==0 | i==0){
                    if(searchResult[i]!=null){
                        lstView.setText(lstView.getText()+title[x] + ": " + searchResult[i]+"\n");
                        lstView.setText(lstView.getText()+title[x+1] + ": " + searchResult[i+1]+"\n");
                        lstView.setText(lstView.getText()+title[x+2] + ": " + searchResult[i+2]+"\n");
                        lstView.setText(lstView.getText()+title[x+3] + ": " + searchResult[i+3]+"\n");
                        lstView.setText(lstView.getText()+title[x+4] + ": " + searchResult[i+4]+"\n");
                    }

                }

            }

        }
    }//GEN-LAST:event_btnSearchOrderActionPerformed

    private void txtSearchOrderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchOrderKeyPressed
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isDigit(c) || Character.isISOControl(c) || c==95)
        {
            txtSearchOrder.setEditable(true);
        }
        else
        {
            txtSearchOrder.setEditable(false);
        }
    }//GEN-LAST:event_txtSearchOrderKeyPressed

    private void btnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderActionPerformed

        try {
            String data [][]=readOrderFile("Order.txt");
            String[] title = {"Customer Name","Name", "Quantity", "Price", "Total"};
            int x=0;
            lm.removeAllElements();
            for(int y=0; y<data.length; y++){
                for(int i=0; i<data.length; i++){
                    if(data[y][0]!=null){
                        if(i==0){
                            lstView.setText(lstView.getText()+title[x]+": "+data[y][0]+"\n");
                            lstView.setText(lstView.getText()+title[x+1]+": "+data[y][1]+"\n");
                            lstView.setText(lstView.getText()+title[x+2]+": "+data[y][2]+"\n");
                            lstView.setText(lstView.getText()+title[x+3]+": "+data[y][3]+"\n");
                            lstView.setText(lstView.getText()+title[x+4]+": "+data[y][4]+"\n");
                        }

                    }
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(Admin_OrderSearchView_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewOrderActionPerformed

    private void btnOrderSearchViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderSearchViewActionPerformed
        
    }//GEN-LAST:event_btnOrderSearchViewActionPerformed

    private void btnAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderActionPerformed
        this.dispose();
        Admin_OrderItem_Menu menu = new Admin_OrderItem_Menu(admin);
        menu.setVisible(true);
    }//GEN-LAST:event_btnAddOrderActionPerformed
    
    public String[][] readOrderFile(String filePath) throws FileNotFoundException, IOException
    {
        //Import file
        String data[][] = new String[50][7]; //100 Row 3 Column (table)
        //Put the whole file into memory
        InputStreamReader reader = new InputStreamReader(new FileInputStream(filePath), "UTF-8");
        //Read line by line from file in memory
        BufferedReader bufReader = new BufferedReader(reader);
        String line;
        int count = 0;

        //Read each line in file
        while((line = bufReader.readLine()) != null)
        {
            //Split the data with : and pass into array
            //Word keep override
            String word[] = line.split(":");

            //Put each line data in word array into the data array after reading each line
            for(int i = 0; i < word.length;i++)
            {
                data[count][i] = word[i];
            }
            //After each line put into data array, move to next line
            count++;
        }
        reader.close();
      
        return data;

    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_OrderSearchView_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_OrderSearchView_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_OrderSearchView_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_OrderSearchView_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_OrderSearchView_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrderEditDelete;
    private javax.swing.JButton btnOrderSearchView;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnSearchOrder;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton btnViewOrder;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblOrderProduct;
    private javax.swing.JTextArea lstView;
    private javax.swing.JTextField txtSearchOrder;
    // End of variables declaration//GEN-END:variables
}
