/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodj_assignment;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
/**
 *
 * @author asus
 */
public class Admin_User_Menu extends javax.swing.JFrame {

    String role = null;
    User user = new User();
    String filePath = "D:\\APU\\Degree Year 2 Sem 1\\OODJ\\Assignment\\User.txt";
            
    DefaultListModel lm = new DefaultListModel(); //Listbox model(contents)
    public Admin_User_Menu() {
        initComponents();
        setSize(950, 650);//Width and Height
        setResizable(false);
        lm.removeAllElements();

        //Control set to false
        btnUserMenu.setEnabled(false);
        btnSignUp.setEnabled(false);
        btnView.setEnabled(false);
        btnSearch.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        rboEditUsername.setEnabled(false);
        rboEditPassword.setEnabled(false);
        txtEditUsername.setEnabled(false);
        txtEditPassword.setEnabled(false);
        
        lstView.setModel(lm); //Attached to the listbox
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsername2 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblPConfirmPassword = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        txtAddUsername = new javax.swing.JTextField();
        txtAddPassword = new javax.swing.JTextField();
        txtConfirmPassword = new javax.swing.JTextField();
        rdoAdmin = new javax.swing.JRadioButton();
        rdoCust = new javax.swing.JRadioButton();
        btnSignUp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstView = new javax.swing.JList<>();
        btnView = new javax.swing.JButton();
        rdoViewCust = new javax.swing.JRadioButton();
        rdoViewAdmin = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        lblUsername1 = new javax.swing.JLabel();
        txtSearchUsername = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtEditUsername = new javax.swing.JTextField();
        txtEditPassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rboEditUsername = new javax.swing.JRadioButton();
        rboEditPassword = new javax.swing.JRadioButton();
        rdoSearchAdmin = new javax.swing.JRadioButton();
        rdoSearchCust = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        btnUserMenu = new javax.swing.JButton();
        btnProductMenu = new javax.swing.JButton();
        btnOrderItemMenu = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnOrderMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setPreferredSize(new java.awt.Dimension(950, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 650));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Sign Up");

        lblUsername2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername2.setText("Username:");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setText("Password:");

        lblPConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPConfirmPassword.setText("Confirm Password:");

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRole.setText("Role:");

        txtAddUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAddUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtAddPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAddPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtConfirmPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        buttonGroup1.add(rdoAdmin);
        rdoAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoAdmin.setText("Admin");
        rdoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAdminActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoCust);
        rdoCust.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoCust.setText("Customer");
        rdoCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCustActionPerformed(evt);
            }
        });

        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRole)
                            .addComponent(lblPConfirmPassword)
                            .addComponent(lblPassword)
                            .addComponent(lblUsername2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rdoAdmin)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdoCust))
                                .addComponent(txtAddPassword)
                                .addComponent(txtAddUsername)
                                .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblUsername2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPConfirmPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRole))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtAddUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAddPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoAdmin)
                            .addComponent(rdoCust))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignUp)
                .addGap(12, 12, 12))
        );

        lstView.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstView);

        btnView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnView.setText("View All Users");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoViewCust);
        rdoViewCust.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoViewCust.setText("Customer");
        rdoViewCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoViewCustActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoViewAdmin);
        rdoViewAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoViewAdmin.setText("Admin");
        rdoViewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoViewAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(rdoViewAdmin)
                        .addGap(18, 18, 18)
                        .addComponent(rdoViewCust)))
                .addGap(118, 118, 118))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoViewAdmin)
                    .addComponent(rdoViewCust))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnView)
                .addGap(12, 12, 12))
        );

        lblUsername1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername1.setText("Username:");

        txtSearchUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtEditUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtEditPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Edit");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Search");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Delete");

        rboEditUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rboEditUsername.setText("Username:");
        rboEditUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboEditUsernameActionPerformed(evt);
            }
        });

        rboEditPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rboEditPassword.setText("Password:");
        rboEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboEditPasswordActionPerformed(evt);
            }
        });

        buttonGroup3.add(rdoSearchAdmin);
        rdoSearchAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoSearchAdmin.setText("Admin");
        rdoSearchAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSearchAdminActionPerformed(evt);
            }
        });

        buttonGroup3.add(rdoSearchCust);
        rdoSearchCust.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoSearchCust.setText("Customer");
        rdoSearchCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSearchCustActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rboEditUsername)
                            .addComponent(rboEditPassword))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEditPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(txtEditUsername)))
                    .addComponent(jLabel3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(20, 20, 20)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblUsername1)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rdoSearchAdmin)
                        .addGap(18, 18, 18)
                        .addComponent(rdoSearchCust)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoSearchAdmin)
                    .addComponent(rdoSearchCust))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername1)
                    .addComponent(txtSearchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rboEditUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rboEditPassword)
                    .addComponent(txtEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addGap(17, 17, 17))
        );

        btnUserMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUserMenu.setText("User Menu");
        btnUserMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserMenuActionPerformed(evt);
            }
        });

        btnProductMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProductMenu.setText("Product Menu");
        btnProductMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductMenuActionPerformed(evt);
            }
        });

        btnOrderItemMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrderItemMenu.setText("Order Items Menu");
        btnOrderItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderItemMenuActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnOrderMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrderMenu.setText("Order Menu");
        btnOrderMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUserMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProductMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrderMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrderItemMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUserMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnProductMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrderItemMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrderMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        if (!txtAddUsername.getText().isBlank() && !txtAddPassword.getText().isBlank())
        {
            try {
                if (user.checkUserExist(filePath, role, txtAddUsername.getText()))
                {
                    JOptionPane.showMessageDialog(this, "User exist! Please try again");
                }
                else
                {
                    user.setNewUsername(txtAddUsername.getText());
                    if (txtAddPassword.getText().equals(txtConfirmPassword.getText()))
                    {
                        user.setNewPassword(txtAddPassword.getText());
                        user.addUser(filePath, role);
                        JOptionPane.showMessageDialog(this, "User successfully added!");
                        txtAddUsername.setText(null);
                        txtAddPassword.setText(null);
                        txtConfirmPassword.setText(null);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Two password are not match!");
                    }

                }
            } catch (IOException ex) {
                Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid input! Please try again");
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void rdoCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCustActionPerformed
        role = "Customer";
        btnSignUp.setEnabled(true);
    }//GEN-LAST:event_rdoCustActionPerformed

    private void rdoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAdminActionPerformed
        role = "Admin";
        btnSignUp.setEnabled(true);
    }//GEN-LAST:event_rdoAdminActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchResult = null;
        lm.removeAllElements();
        
        try {
            searchResult = user.searchUser(filePath, role, txtSearchUsername.getText());
        } catch (IOException ex) {
            Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (searchResult==null)
        {
            lm.addElement("User not Found!");
            rboEditUsername.setEnabled(false);
            rboEditPassword.setEnabled(false);
            btnDelete.setEnabled(false);
        }
        else
        {
            lm.addElement("Search Result:");
            lm.addElement("Role : ID : Username : Password");
            lm.addElement(searchResult);
            rboEditUsername.setEnabled(true);
            rboEditPassword.setEnabled(true);
            btnDelete.setEnabled(true);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        lm.addElement(role);
        lm.addElement("Role : ID : Username : Password");
        String[] userList = null;
        try {
            userList = user.viewUser(filePath, role);
        } catch (IOException ex) {
            Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < userList.length; i++)
        {
            if (userList[i]!=null)
            {
                lm.addElement(userList[i]);
            }
        }
        lm.addElement("");
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (!txtEditUsername.getText().isBlank() && !txtEditPassword.getText().isBlank() && rboEditUsername.isSelected() && rboEditPassword.isSelected())
        {
            try {
                if (user.checkUserExist(filePath, role, txtEditUsername.getText()))
                {
                    JOptionPane.showMessageDialog(this, "User exist! Please try again");
                }
                else
                {
                    try {
                        user.editUserDetails(filePath, role, txtSearchUsername.getText(), txtEditUsername.getText(), txtEditPassword.getText());
                    } catch (IOException ex) {
                        Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (!txtEditUsername.getText().isBlank() && !rboEditPassword.isSelected())
        {
            try {
                if (user.checkUserExist(filePath, role, txtEditUsername.getText()))
                {
                    JOptionPane.showMessageDialog(this, "User exist! Please try again");
                }
                else
                {
                    try {
                        user.editUserDetails(filePath, role, txtSearchUsername.getText(), txtEditUsername.getText());
                    } catch (IOException ex) {
                        Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (!txtEditPassword.getText().isBlank() && !rboEditUsername.isSelected())
        {
            try {
                user.editUserDetails(filePath, role, txtSearchUsername.getText(), txtSearchUsername.getText(), txtEditPassword.getText());
            } catch (IOException ex) {
                Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid input! Please try again!");
        }
        lm.addElement("\n");
        lm.addElement("After Edit:");
        lm.addElement("Role : ID : Username : Password");
        try {
            lm.addElement(user.searchUser(filePath, role, txtEditUsername.getText()));
        } catch (IOException ex) {
            Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtEditUsername.setText(null);
        txtEditPassword.setText(null);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try { 
            user.deleteUser(filePath, role, txtSearchUsername.getText());
        } catch (IOException ex) {
            Logger.getLogger(Admin_User_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "User successfully deleted!");
        txtSearchUsername.setText(null);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUserMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserMenuActionPerformed

    private void btnProductMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductMenuActionPerformed

    private void btnOrderItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderItemMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderItemMenuActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnOrderMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderMenuActionPerformed
        
    }//GEN-LAST:event_btnOrderMenuActionPerformed

    private void rdoViewCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoViewCustActionPerformed
        role = "Customer";
        btnView.setEnabled(true);
    }//GEN-LAST:event_rdoViewCustActionPerformed

    private void rdoViewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoViewAdminActionPerformed
        role = "Admin";
        btnView.setEnabled(true);
    }//GEN-LAST:event_rdoViewAdminActionPerformed

    private void rdoSearchAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSearchAdminActionPerformed
        role = "Admin";
        btnSearch.setEnabled(true);
    }//GEN-LAST:event_rdoSearchAdminActionPerformed

    private void rdoSearchCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSearchCustActionPerformed
        role = "Customer";
        btnSearch.setEnabled(true);
    }//GEN-LAST:event_rdoSearchCustActionPerformed

    private void rboEditUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboEditUsernameActionPerformed
        if (rboEditUsername.isSelected() && rboEditPassword.isSelected())
        {
            txtEditUsername.setEnabled(true);
            txtEditPassword.setEnabled(true);
            btnEdit.setEnabled(true);
        }
        else if (rboEditUsername.isSelected() && !rboEditPassword.isSelected())
        {
            txtEditUsername.setEnabled(true);
            txtEditPassword.setEnabled(false);
            btnEdit.setEnabled(true);
        }
        else if (!rboEditUsername.isSelected() && rboEditPassword.isSelected())
        {
            txtEditUsername.setEnabled(false);
            txtEditPassword.setEnabled(true);
            btnEdit.setEnabled(true);
        }
        else
        {
            txtEditUsername.setEnabled(false);
            btnEdit.setEnabled(false);
        }
        
    }//GEN-LAST:event_rboEditUsernameActionPerformed

    private void rboEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboEditPasswordActionPerformed
        if (rboEditUsername.isSelected() && rboEditPassword.isSelected())
        {
            txtEditUsername.setEnabled(true);
            txtEditPassword.setEnabled(true);
            btnEdit.setEnabled(true);
        }
        else if (rboEditUsername.isSelected() && !rboEditPassword.isSelected())
        {
            txtEditUsername.setEnabled(true);
            txtEditPassword.setEnabled(false);
            btnEdit.setEnabled(true);
        }
        else if (!rboEditUsername.isSelected() && rboEditPassword.isSelected())
        {
            txtEditUsername.setEnabled(false);
            txtEditPassword.setEnabled(true);
            btnEdit.setEnabled(true);
        }
        else
        {
            txtEditUsername.setEnabled(false);
            btnEdit.setEnabled(false);
        }
        
    }//GEN-LAST:event_rboEditPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_User_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_User_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_User_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_User_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_User_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrderItemMenu;
    private javax.swing.JButton btnOrderMenu;
    private javax.swing.JButton btnProductMenu;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton btnUserMenu;
    private javax.swing.JButton btnView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPConfirmPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel lblUsername2;
    private javax.swing.JList<String> lstView;
    private javax.swing.JRadioButton rboEditPassword;
    private javax.swing.JRadioButton rboEditUsername;
    private javax.swing.JRadioButton rdoAdmin;
    private javax.swing.JRadioButton rdoCust;
    private javax.swing.JRadioButton rdoSearchAdmin;
    private javax.swing.JRadioButton rdoSearchCust;
    private javax.swing.JRadioButton rdoViewAdmin;
    private javax.swing.JRadioButton rdoViewCust;
    private javax.swing.JTextField txtAddPassword;
    private javax.swing.JTextField txtAddUsername;
    private javax.swing.JTextField txtConfirmPassword;
    private javax.swing.JTextField txtEditPassword;
    private javax.swing.JTextField txtEditUsername;
    private javax.swing.JTextField txtSearchUsername;
    // End of variables declaration//GEN-END:variables
}
