/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodj_assignment;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;

public class Admin_Product_Menu extends javax.swing.JFrame {

    String newType = null;
    String editType = null;
    String viewType = null;
    Product product = new Product();
    int newPriceCount = 0;
    int newPriceDp = 0;
    int editPriceCount = 0;
    int editPriceDp = 0;
    int newWeightCount = 0;
    int newWeightDp = 0;
    int editWeightCount = 0;
    int editWeightDp = 0;

    private Admin_Product_Menu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    enum Type
    {
        Fragile,
        NonFragile
    }
     
    UserLogin loginProduct = new UserLogin();
    
    DefaultListModel lm = new DefaultListModel(); //Listbox model(contents)
    public Admin_Product_Menu(UserLogin loginUser) {
        initComponents();
        setSize(1000, 680);//Width and Height
        setResizable(false);
        lblRole.setText(loginUser.getRole());
        lblId.setText(loginUser.getId());
        lblUsername.setText(loginUser.getUsername());
        loginProduct = loginUser;
        lm.removeAllElements();

        //Control set to false
        btnProductMenu.setEnabled(false);
        btnAdd.setEnabled(false);
        btnView.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        txtEditName.setEnabled(false);
        txtEditPrice.setEnabled(false);
        rdoEditFragile.setEnabled(false);
        rdoEditNonFragile.setEnabled(false);
        txtEditQuantity.setEnabled(false);
        txtEditWeight.setEnabled(false);
        rdoEditName.setEnabled(false);
        rdoEditPrice.setEnabled(false);
        rdoEditType.setEnabled(false);
        rdoEditQuantity.setEnabled(false);
        rdoEditWeight.setEnabled(false);
        lstView.setModel(lm); //Attached to the listbox
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsername2 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblPConfirmPassword = new javax.swing.JLabel();
        lblPConfirmPassword1 = new javax.swing.JLabel();
        txtNewPrice = new javax.swing.JTextField();
        cboNewCategory = new javax.swing.JComboBox<>();
        lblPConfirmPassword3 = new javax.swing.JLabel();
        txtNewQuantity = new javax.swing.JTextField();
        lblType = new javax.swing.JLabel();
        rdoNewNonFragile = new javax.swing.JRadioButton();
        rdoNewFragile = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        lblUsername6 = new javax.swing.JLabel();
        txtNewWeight = new javax.swing.JTextField();
        btnNewAddCategory = new javax.swing.JButton();
        txtNewCategory = new javax.swing.JTextField();
        txtNewName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstView = new javax.swing.JList<>();
        btnView = new javax.swing.JButton();
        rdoViewNonFragile = new javax.swing.JRadioButton();
        rdoViewFragile = new javax.swing.JRadioButton();
        lblUsername = new javax.swing.JLabel();
        lblID1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblRole1 = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblUsername3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblUsername1 = new javax.swing.JLabel();
        txtSearchProduct = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEditName = new javax.swing.JTextField();
        txtEditPrice = new javax.swing.JTextField();
        rdoEditFragile = new javax.swing.JRadioButton();
        rdoEditNonFragile = new javax.swing.JRadioButton();
        txtEditQuantity = new javax.swing.JTextField();
        txtEditWeight = new javax.swing.JTextField();
        lblUsername5 = new javax.swing.JLabel();
        rdoEditPrice = new javax.swing.JRadioButton();
        rdoEditName = new javax.swing.JRadioButton();
        rdoEditType = new javax.swing.JRadioButton();
        rdoEditQuantity = new javax.swing.JRadioButton();
        rdoEditWeight = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        btnUserMenu = new javax.swing.JButton();
        btnProductMenu = new javax.swing.JButton();
        btnOrderItemMenu = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnOrderMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 650));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("New Product");

        lblUsername2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername2.setText("Name:");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setText("Price (RM):");

        lblPConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPConfirmPassword.setText("Quantity:");

        lblPConfirmPassword1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPConfirmPassword1.setText("Category:");

        txtNewPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNewPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtNewPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewPriceFocusLost(evt);
            }
        });
        txtNewPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewPriceKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewPriceKeyTyped(evt);
            }
        });

        cboNewCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seasoning", "Beverage", "Bread", "Stationary" }));

        lblPConfirmPassword3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPConfirmPassword3.setText("Weight:");

        txtNewQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNewQuantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtNewQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewQuantityKeyPressed(evt);
            }
        });

        lblType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblType.setText("Types:");

        buttonGroup1.add(rdoNewNonFragile);
        rdoNewNonFragile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoNewNonFragile.setText("Non-Fragile");
        rdoNewNonFragile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNewNonFragileActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoNewFragile);
        rdoNewFragile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoNewFragile.setText("Fragile");
        rdoNewFragile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNewFragileActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblUsername6.setText("(KG each)");

        txtNewWeight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNewWeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtNewWeight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewWeightFocusLost(evt);
            }
        });
        txtNewWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewWeightKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewWeightKeyTyped(evt);
            }
        });

        btnNewAddCategory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNewAddCategory.setText("+");
        btnNewAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAddCategoryActionPerformed(evt);
            }
        });

        txtNewCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNewCategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtNewCategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewCategoryKeyPressed(evt);
            }
        });

        txtNewName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNewName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtNewName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewNameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblUsername2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblType)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPConfirmPassword1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboNewCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdoNewFragile))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoNewNonFragile)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtNewCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNewAddCategory))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPConfirmPassword)
                                .addGap(21, 21, 21)
                                .addComponent(txtNewQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPConfirmPassword3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNewWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUsername6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername2)
                            .addComponent(txtNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPassword))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(txtNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(rdoNewFragile)
                    .addComponent(rdoNewNonFragile))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPConfirmPassword1)
                    .addComponent(cboNewCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPConfirmPassword)
                    .addComponent(lblPConfirmPassword3)
                    .addComponent(txtNewQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername6)
                    .addComponent(txtNewWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(29, 29, 29))
        );

        lstView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(lstView);

        btnView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnView.setText("View All Product");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoViewNonFragile);
        rdoViewNonFragile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoViewNonFragile.setText("Non Fragile");
        rdoViewNonFragile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoViewNonFragileActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoViewFragile);
        rdoViewFragile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoViewFragile.setText("Fragile");
        rdoViewFragile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoViewFragileActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setText("Username");

        lblID1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblID1.setText("Username:");

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblId.setText("ID");

        lblRole1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRole1.setText("ID:");

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRole.setText("Role");

        lblUsername3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername3.setText("Role:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 110, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnView))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdoViewFragile)
                                .addGap(18, 18, 18)
                                .addComponent(rdoViewNonFragile)))
                        .addGap(104, 104, 104))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblUsername3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRole)
                        .addGap(18, 18, 18)
                        .addComponent(lblRole1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblId)
                        .addGap(18, 18, 18)
                        .addComponent(lblID1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsername)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername3)
                    .addComponent(lblRole)
                    .addComponent(lblRole1)
                    .addComponent(lblId)
                    .addComponent(lblID1)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoViewFragile)
                    .addComponent(rdoViewNonFragile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnView)
                .addGap(12, 12, 12))
        );

        lblUsername1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername1.setText("Name:");

        txtSearchProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtSearchProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchProductKeyPressed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Edit");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Search");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Delete");

        txtEditName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtEditName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEditNameKeyPressed(evt);
            }
        });

        txtEditPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtEditPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEditPriceFocusLost(evt);
            }
        });
        txtEditPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEditPriceKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditPriceKeyTyped(evt);
            }
        });

        buttonGroup3.add(rdoEditFragile);
        rdoEditFragile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoEditFragile.setText("Fragile");
        rdoEditFragile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoEditFragileActionPerformed(evt);
            }
        });

        buttonGroup3.add(rdoEditNonFragile);
        rdoEditNonFragile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoEditNonFragile.setText("Non-Fragile");
        rdoEditNonFragile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoEditNonFragileActionPerformed(evt);
            }
        });

        txtEditQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditQuantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtEditQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEditQuantityKeyPressed(evt);
            }
        });

        txtEditWeight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditWeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtEditWeight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEditWeightFocusLost(evt);
            }
        });
        txtEditWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEditWeightKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditWeightKeyTyped(evt);
            }
        });

        lblUsername5.setText("(KG)");

        rdoEditPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoEditPrice.setText("Price (RM):");
        rdoEditPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoEditPriceActionPerformed(evt);
            }
        });

        rdoEditName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoEditName.setText("Name:");
        rdoEditName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoEditNameActionPerformed(evt);
            }
        });

        rdoEditType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoEditType.setText("Type:");
        rdoEditType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoEditTypeActionPerformed(evt);
            }
        });

        rdoEditQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoEditQuantity.setText("Quantity:");
        rdoEditQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoEditQuantityActionPerformed(evt);
            }
        });

        rdoEditWeight.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoEditWeight.setText("Weight:");
        rdoEditWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoEditWeightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblUsername1)
                                .addGap(28, 28, 28)
                                .addComponent(txtSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(rdoEditName)
                            .addComponent(rdoEditPrice)
                            .addComponent(rdoEditType)
                            .addComponent(rdoEditQuantity)
                            .addComponent(rdoEditWeight))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rdoEditFragile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoEditNonFragile))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEditPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEditName, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEditWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEditQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblUsername5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername1)
                    .addComponent(txtSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoEditName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoEditPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoEditFragile)
                    .addComponent(rdoEditNonFragile)
                    .addComponent(rdoEditType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoEditQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername5)
                    .addComponent(rdoEditWeight)
                    .addComponent(btnEdit))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnUserMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUserMenu.setText("User Menu");
        btnUserMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserMenuActionPerformed(evt);
            }
        });

        btnProductMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProductMenu.setText("Product Menu");
        btnProductMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductMenuActionPerformed(evt);
            }
        });

        btnOrderItemMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrderItemMenu.setText("Order Items Menu");
        btnOrderItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderItemMenuActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnOrderMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrderMenu.setText("Order Menu");
        btnOrderMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUserMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProductMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrderMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrderItemMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProductMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrderItemMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrderMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUserMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String searchResult[] = null;
        lm.removeAllElements();
        String[] title = {"Category", "ID", "Product Name", "Type", "Price", "Quantity", "Weight"};
        if (!txtNewName.getText().isBlank() && !txtNewPrice.getText().isBlank() && !txtNewQuantity.getText().isBlank())
        {
            try {
                if (product.checkProductExist(txtNewName.getText()))
                {
                    JOptionPane.showMessageDialog(this, "Product exist! Please try again");
                }
                else
                {
                    product.setProName(txtNewName.getText());
                    product.addProduct(cboNewCategory.getSelectedItem().toString(), txtNewName.getText(), newType, txtNewPrice.getText(), txtNewQuantity.getText(), txtNewWeight.getText());
                    try {
                        searchResult = product.searchProName(txtNewName.getText());
                    } catch (IOException ex) {
                        Logger.getLogger(Admin_Product_Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    lm.addElement("<html><b>New Product:<html><b>");
                    for (int i=0; i<title.length;i++)
                    {
                        lm.addElement(title[i] + ": " + searchResult[i]);
                    }
                    JOptionPane.showMessageDialog(this, "Product successfully added!");
                }
            } catch (IOException ex) {
                Logger.getLogger(Admin_Product_Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid input! Please try again");
        }
        txtNewName.setText(null);
        txtNewPrice.setText(null);
        txtNewQuantity.setText(null);
        txtNewWeight.setText(null);
        txtNewCategory.setText(null);
        buttonGroup1.clearSelection();
        btnAdd.setEnabled(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        lm.removeAllElements();
        lm.addElement("<html><b>"+viewType+"</b></html>");
        String[] title = {"Category", "ID", "Product Name", "Type", "Price", "Quantity", "Weight"};
        String[][] productList = null;
        try {
            productList = product.viewProduct(viewType);
        } catch (IOException ex) {
            Logger.getLogger(Admin_Product_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < productList.length; i++)
        {
            if (productList[i]!=null)
            {
                if (productList[i][0]!=null)
                {
                    lm.addElement(title[0] + ": " + productList[i][0]);
                    lm.addElement(title[1] + ": " + productList[i][1]);
                    lm.addElement(title[2] + ": " + productList[i][2]);
                    lm.addElement(title[3] + ": " + productList[i][3]);
                    lm.addElement(title[4] + ": " + productList[i][4]);
                    lm.addElement(title[5] + ": " + productList[i][5]);
                    lm.addElement(title[6] + ": " + productList[i][6]);
                    lm.addElement("\n");
                }
            }
        }
        lm.addElement("\n");
        buttonGroup2.clearSelection();
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUserMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserMenuActionPerformed
        this.dispose();
        Admin_User_Menu userMenu = new Admin_User_Menu(loginProduct);
        userMenu.setVisible(true);
    }//GEN-LAST:event_btnUserMenuActionPerformed

    private void btnProductMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductMenuActionPerformed

    private void btnOrderItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderItemMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderItemMenuActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnOrderMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderMenuActionPerformed
        
    }//GEN-LAST:event_btnOrderMenuActionPerformed

    private void rdoViewNonFragileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoViewNonFragileActionPerformed
        Type type = Type.NonFragile;
        viewType = type.toString();
        btnView.setEnabled(true);
    }//GEN-LAST:event_rdoViewNonFragileActionPerformed

    private void rdoViewFragileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoViewFragileActionPerformed
        Type type = Type.Fragile;
        viewType = type.toString();
        btnView.setEnabled(true);
    }//GEN-LAST:event_rdoViewFragileActionPerformed

    private void rdoNewFragileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNewFragileActionPerformed
        Type type = Type.Fragile;
        newType = type.toString();
        btnAdd.setEnabled(true);
    }//GEN-LAST:event_rdoNewFragileActionPerformed

    private void rdoNewNonFragileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNewNonFragileActionPerformed
        Type type = Type.NonFragile;
        newType = type.toString();
        btnAdd.setEnabled(true);
    }//GEN-LAST:event_rdoNewNonFragileActionPerformed

    private void txtNewPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPriceKeyPressed
        char c = evt.getKeyChar();

        if (Character.isDigit(c) || Character.isISOControl(c) || c==46)
        {
            txtNewPrice.setEditable(true);
        }
        else
        {
            txtNewPrice.setEditable(false);
        }
    }//GEN-LAST:event_txtNewPriceKeyPressed

    private void txtNewQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewQuantityKeyPressed
        char c = evt.getKeyChar();
        
        if (Character.isDigit(c) || Character.isISOControl(c))
        {
            txtNewQuantity.setEditable(true);
        }
        else
        {
            txtNewQuantity.setEditable(false);
        }
    }//GEN-LAST:event_txtNewQuantityKeyPressed

    private void btnNewAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAddCategoryActionPerformed
        if (!txtNewCategory.getText().isBlank())
        {
            cboNewCategory.addItem(txtNewCategory.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid input! Please try again!");
        }
    }//GEN-LAST:event_btnNewAddCategoryActionPerformed

    private void txtNewNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewNameKeyPressed
        char c = evt.getKeyChar();
        
        if (Character.isLetter(c) || Character.isDigit(c) || Character.isISOControl(c) || c==95)
        {
            txtNewName.setEditable(true);
        }
        else
        {
            txtNewName.setEditable(false);
        }
    }//GEN-LAST:event_txtNewNameKeyPressed

    private void txtNewCategoryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewCategoryKeyPressed
        char c = evt.getKeyChar();
        
        if (Character.isLetter(c) || Character.isDigit(c) || Character.isISOControl(c) || c==95)
        {
            txtNewCategory.setEditable(true);
        }
        else
        {
            txtNewCategory.setEditable(false);
        }
    }//GEN-LAST:event_txtNewCategoryKeyPressed

    private void txtNewWeightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewWeightKeyPressed
        char c = evt.getKeyChar();

        if (Character.isDigit(c) || Character.isISOControl(c) || c==46)
        {
            txtNewWeight.setEditable(true);
        }
        else
        {
            txtNewWeight.setEditable(false);
        }
    }//GEN-LAST:event_txtNewWeightKeyPressed

    private void txtEditWeightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditWeightKeyPressed
        char c = evt.getKeyChar();

        if (Character.isDigit(c) || Character.isISOControl(c) || c==46)
        {
            txtEditWeight.setEditable(true);
        }
        else
        {
            txtEditWeight.setEditable(false);
        }
    }//GEN-LAST:event_txtEditWeightKeyPressed

    private void txtEditQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditQuantityKeyPressed
        char c = evt.getKeyChar();

        if (Character.isDigit(c) || Character.isISOControl(c))
        {
            txtEditQuantity.setEditable(true);
        }
        else
        {
            txtEditQuantity.setEditable(false);
        }
    }//GEN-LAST:event_txtEditQuantityKeyPressed

    private void rdoEditNonFragileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoEditNonFragileActionPerformed
        Type type = Type.NonFragile;
        editType = type.toString();
    }//GEN-LAST:event_rdoEditNonFragileActionPerformed

    private void rdoEditFragileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoEditFragileActionPerformed
        Type type = Type.Fragile;
        editType = type.toString();
    }//GEN-LAST:event_rdoEditFragileActionPerformed

    private void txtEditPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditPriceKeyPressed
        char c = evt.getKeyChar();

        if (Character.isDigit(c) || Character.isISOControl(c) || c==46)
        {
            txtEditPrice.setEditable(true);
        }
        else
        {
            txtEditPrice.setEditable(false);
        }
    }//GEN-LAST:event_txtEditPriceKeyPressed

    private void txtEditNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditNameKeyPressed
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isDigit(c) || Character.isISOControl(c) || c==95)
        {
            txtEditName.setEditable(true);
        }
        else
        {
            txtEditName.setEditable(false);
        }
    }//GEN-LAST:event_txtEditNameKeyPressed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            product.deleteProduct(txtSearchProduct.getText());
        } catch (IOException ex) {
            Logger.getLogger(Admin_Product_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Product successfully deleted!");
        txtSearchProduct.setText(null);
        btnDelete.setEnabled(false);
        rdoEditName.setEnabled(false);
        rdoEditName.setSelected(false);
        rdoEditPrice.setEnabled(false);
        rdoEditPrice.setSelected(false);
        rdoEditType.setEnabled(false);
        rdoEditType.setSelected(false);
        rdoEditQuantity.setEnabled(false);
        rdoEditQuantity.setSelected(false);
        rdoEditWeight.setEnabled(false);
        rdoEditWeight.setSelected(false);
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String editName = null; 
        String editPrice = null;
        String editProType = null; 
        String editQuantity = null;
        String editWeight = null; 
        boolean print = true;
        String[] searchResult = null;
        String[] title = {"Category", "ID", "Product Name", "Type", "Price", "Quantity", "Weight"};
        try {
            searchResult = product.searchProName(txtSearchProduct.getText());
        } catch (IOException ex) {
            Logger.getLogger(Admin_Product_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Edit name
        if (rdoEditName.isSelected() && !txtEditName.getText().isBlank())
        {
            try {
                if (product.checkProductExist(txtEditName.getText()))
                {
                    JOptionPane.showMessageDialog(this, "Product exist! Please try again");
                    print = false;
                }
                else
                {
                    editName=txtEditName.getText();
                }
            } catch (IOException ex) {
                Logger.getLogger(Admin_Product_Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            editName=searchResult[2];
        }
        //Edit Type
        if (rdoEditType.isSelected()  && (rdoEditFragile.isSelected() || rdoEditNonFragile.isSelected()))
        {
            editProType=editType;
        }
        else
        {
            editProType=searchResult[3];
        }
        //Edit price
        if (rdoEditPrice.isSelected() && !txtEditPrice.getText().isBlank())
        {
            editPrice=txtEditPrice.getText();
        }
        else
        {
            editPrice=searchResult[4];
        }
        //Edit Quantity
        if (rdoEditQuantity.isSelected() && !txtEditQuantity.getText().isBlank())
        {
            editQuantity=txtEditQuantity.getText();
        }
        else
        {
            editQuantity=searchResult[5];
        }
        //Edit Weight
        if (rdoEditWeight.isSelected() && !txtEditWeight.getText().isBlank())
        {
            editWeight=txtEditWeight.getText();
        }
        else
        {
            editWeight=searchResult[6];
        }
        if (print == true)
        {
            try {
                product.editProductDetails(txtSearchProduct.getText(), editName, editProType, editPrice, editQuantity ,editWeight);
            } catch (IOException ex) {
                Logger.getLogger(Admin_Product_Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            lm.addElement("\n");
            lm.addElement("<html><b>After Edit:<html><b>");
            if (!rdoEditName.isSelected())
            {
                try {
                    searchResult = product.searchProName(txtSearchProduct.getText());
                } catch (IOException ex) {
                    Logger.getLogger(Admin_Product_Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
                for (int i=0; i<title.length;i++)
                {
                    lm.addElement(title[i] + ": " + searchResult[i]);
                }
            }
            else
            {
                try {
                    searchResult = product.searchProName(txtEditName.getText());
                } catch (IOException ex) {
                    Logger.getLogger(Admin_Product_Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
                for (int i=0; i<title.length;i++)
                {
                    lm.addElement(title[i] + ": " + searchResult[i]);
                }
            }
        }
        txtSearchProduct.setText(null);
        txtEditName.setText(null);
        txtEditName.setEnabled(false);
        txtEditPrice.setText(null);
        txtEditPrice.setEnabled(false);
        buttonGroup3.clearSelection();
        rdoEditFragile.setEnabled(false);
        rdoEditNonFragile.setEnabled(false);
        txtEditQuantity.setText(null);
        txtEditQuantity.setEnabled(false);
        txtEditWeight.setText(null);
        txtEditWeight.setEnabled(false);
        rdoEditName.setEnabled(false);
        rdoEditName.setSelected(false);
        rdoEditPrice.setEnabled(false);
        rdoEditPrice.setSelected(false);
        rdoEditType.setEnabled(false);
        rdoEditType.setSelected(false);
        rdoEditQuantity.setEnabled(false);
        rdoEditQuantity.setSelected(false);
        rdoEditWeight.setEnabled(false);
        rdoEditWeight.setSelected(false);
        btnDelete.setEnabled(false);
        btnEdit.setEnabled(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchResult[] = null;
        lm.removeAllElements();
        String[] title = {"Category", "ID", "Product Name", "Type", "Price", "Quantity", "Weight"};
        try {
            searchResult = product.searchProName(txtSearchProduct.getText());
        } catch (IOException ex) {
            Logger.getLogger(Admin_Product_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (searchResult[2]==null)
        {
            lm.addElement("<html><b>Product Not Found!<html><b>");
            btnDelete.setEnabled(false);
            txtSearchProduct.setText(null);
        }
        else
        {
            lm.addElement("<html><b>Search Result:<html><b>");
            for (int i=0; i<title.length;i++)
            {
                lm.addElement(title[i] + ": " + searchResult[i]);
            }
            btnDelete.setEnabled(true);
            rdoEditName.setEnabled(true);
            rdoEditPrice.setEnabled(true);
            rdoEditType.setEnabled(true);
            rdoEditQuantity.setEnabled(true);
            rdoEditWeight.setEnabled(true);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchProductKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchProductKeyPressed
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isDigit(c) || Character.isISOControl(c) || c==95)
        {
            txtSearchProduct.setEditable(true);
        }
        else
        {
            txtSearchProduct.setEditable(false);
        }
    }//GEN-LAST:event_txtSearchProductKeyPressed

    private void rdoEditNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoEditNameActionPerformed
        if (rdoEditName.isSelected() || rdoEditPrice.isSelected() || rdoEditType.isSelected() || rdoEditQuantity.isSelected() || rdoEditWeight.isSelected())
        {
            btnEdit.setEnabled(true);
        }
        else
        {
            btnEdit.setEnabled(false);
        }
        
        if (rdoEditName.isSelected())
        {
            txtEditName.setEnabled(true);                
        }
        else
        {
            txtEditName.setEnabled(false);
        }
        if (rdoEditPrice.isSelected())
        {
            txtEditPrice.setEnabled(true);
        }
        else
        {
            txtEditPrice.setEnabled(false);
        }
        if (rdoEditType.isSelected())
        {
            rdoEditFragile.setEnabled(true);
            rdoEditNonFragile.setEnabled(true);
        }
        else
        {
            rdoEditFragile.setEnabled(false);
            rdoEditNonFragile.setEnabled(false);
        }
        if (rdoEditQuantity.isSelected())
        {
            txtEditQuantity.setEnabled(true);
        }
        else
        {
            txtEditQuantity.setEnabled(false);
        }
        if (rdoEditWeight.isSelected())
        {
            txtEditWeight.setEnabled(true);
        }
        else
        {
            txtEditWeight.setEnabled(false);
        }

    }//GEN-LAST:event_rdoEditNameActionPerformed

    private void rdoEditPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoEditPriceActionPerformed
        if (rdoEditName.isSelected() || rdoEditPrice.isSelected() || rdoEditType.isSelected() || rdoEditQuantity.isSelected() || rdoEditWeight.isSelected())
        {
            btnEdit.setEnabled(true);
        }
        else
        {
            btnEdit.setEnabled(false);
        }
        
        if (rdoEditName.isSelected())
        {
            txtEditName.setEnabled(true);                
        }
        else
        {
            txtEditName.setEnabled(false);
        }
        if (rdoEditPrice.isSelected())
        {
            txtEditPrice.setEnabled(true);
        }
        else
        {
            txtEditPrice.setEnabled(false);
        }
        if (rdoEditType.isSelected())
        {
            rdoEditFragile.setEnabled(true);
            rdoEditNonFragile.setEnabled(true);
        }
        else
        {
            rdoEditFragile.setEnabled(false);
            rdoEditNonFragile.setEnabled(false);
        }
        if (rdoEditQuantity.isSelected())
        {
            txtEditQuantity.setEnabled(true);
        }
        else
        {
            txtEditQuantity.setEnabled(false);
        }
        if (rdoEditWeight.isSelected())
        {
            txtEditWeight.setEnabled(true);
        }
        else
        {
            txtEditWeight.setEnabled(false);
        }
    }//GEN-LAST:event_rdoEditPriceActionPerformed

    private void rdoEditTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoEditTypeActionPerformed
        if (rdoEditName.isSelected() || rdoEditPrice.isSelected() || rdoEditType.isSelected() || rdoEditQuantity.isSelected() || rdoEditWeight.isSelected())
        {
            btnEdit.setEnabled(true);
        }
        else
        {
            btnEdit.setEnabled(false);
        }
        
        if (rdoEditName.isSelected())
        {
            txtEditName.setEnabled(true);                
        }
        else
        {
            txtEditName.setEnabled(false);
        }
        if (rdoEditPrice.isSelected())
        {
            txtEditPrice.setEnabled(true);
        }
        else
        {
            txtEditPrice.setEnabled(false);
        }
        if (rdoEditType.isSelected())
        {
            rdoEditFragile.setEnabled(true);
            rdoEditNonFragile.setEnabled(true);
        }
        else
        {
            rdoEditFragile.setEnabled(false);
            rdoEditNonFragile.setEnabled(false);
        }
        if (rdoEditQuantity.isSelected())
        {
            txtEditQuantity.setEnabled(true);
        }
        else
        {
            txtEditQuantity.setEnabled(false);
        }
        if (rdoEditWeight.isSelected())
        {
            txtEditWeight.setEnabled(true);
        }
        else
        {
            txtEditWeight.setEnabled(false);
        }
    }//GEN-LAST:event_rdoEditTypeActionPerformed

    private void rdoEditQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoEditQuantityActionPerformed
        if (rdoEditName.isSelected() || rdoEditPrice.isSelected() || rdoEditType.isSelected() || rdoEditQuantity.isSelected() || rdoEditWeight.isSelected())
        {
            btnEdit.setEnabled(true);
        }
        else
        {
            btnEdit.setEnabled(false);
        }
        
        if (rdoEditName.isSelected())
        {
            txtEditName.setEnabled(true);                
        }
        else
        {
            txtEditName.setEnabled(false);
        }
        if (rdoEditPrice.isSelected())
        {
            txtEditPrice.setEnabled(true);
        }
        else
        {
            txtEditPrice.setEnabled(false);
        }
        if (rdoEditType.isSelected())
        {
            rdoEditFragile.setEnabled(true);
            rdoEditNonFragile.setEnabled(true);
        }
        else
        {
            rdoEditFragile.setEnabled(false);
            rdoEditNonFragile.setEnabled(false);
        }
        if (rdoEditQuantity.isSelected())
        {
            txtEditQuantity.setEnabled(true);
        }
        else
        {
            txtEditQuantity.setEnabled(false);
        }
        if (rdoEditWeight.isSelected())
        {
            txtEditWeight.setEnabled(true);
        }
        else
        {
            txtEditWeight.setEnabled(false);
        }
    }//GEN-LAST:event_rdoEditQuantityActionPerformed

    private void rdoEditWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoEditWeightActionPerformed
        if (rdoEditName.isSelected() || rdoEditPrice.isSelected() || rdoEditType.isSelected() || rdoEditQuantity.isSelected() || rdoEditWeight.isSelected())
        {
            btnEdit.setEnabled(true);
        }
        else
        {
            btnEdit.setEnabled(false);
        }
        
        if (rdoEditName.isSelected())
        {
            txtEditName.setEnabled(true);                
        }
        else
        {
            txtEditName.setEnabled(false);
        }
        if (rdoEditPrice.isSelected())
        {
            txtEditPrice.setEnabled(true);
        }
        else
        {
            txtEditPrice.setEnabled(false);
        }
        if (rdoEditType.isSelected())
        {
            rdoEditFragile.setEnabled(true);
            rdoEditNonFragile.setEnabled(true);
        }
        else
        {
            rdoEditFragile.setEnabled(false);
            rdoEditNonFragile.setEnabled(false);
        }
        if (rdoEditQuantity.isSelected())
        {
            txtEditQuantity.setEnabled(true);
        }
        else
        {
            txtEditQuantity.setEnabled(false);
        }
        if (rdoEditWeight.isSelected())
        {
            txtEditWeight.setEnabled(true);
        }
        else
        {
            txtEditWeight.setEnabled(false);
        }
    }//GEN-LAST:event_rdoEditWeightActionPerformed

    private void txtNewPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPriceKeyTyped
        try{
            Double.parseDouble(txtNewPrice.getText()+evt.getKeyChar());
            if (evt.getKeyChar()=='.')
            {
                newPriceCount=1;
            }
            if (Character.isISOControl(evt.getKeyChar()))
            {
                if (txtNewPrice.getText().contains("."))
                {
                    newPriceDp=newPriceDp-2;
                    if (newPriceDp==0)
                    {
                        newPriceDp=0;
                    }
                }
                else
                {
                    newPriceCount=0;
                newPriceDp=0;
                }
            }
            if (newPriceCount==1)
            {
                newPriceDp++;
                if (newPriceDp>3) //Adjust this to change the decimal places
                {
                    newPriceDp=3;
                    evt.consume();
                }
            } 
        }
        catch (NumberFormatException ex)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtNewPriceKeyTyped

    private void txtNewPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPriceFocusLost
        if (txtNewPrice.getText().contains("."))
            {
                newPriceCount=1;
            }
            else
            {
                newPriceCount=0;
                newPriceDp=0;
            }
    }//GEN-LAST:event_txtNewPriceFocusLost

    private void txtNewWeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewWeightKeyTyped
        try{
            Double.parseDouble(txtNewWeight.getText()+evt.getKeyChar());
            if (evt.getKeyChar()=='.')
            {
                newWeightCount=1;
            }
            if (Character.isISOControl(evt.getKeyChar()))
            {
                if (txtNewWeight.getText().contains("."))
                {
                    newWeightDp=newWeightDp-2;
                    if (newWeightDp==0)
                    {
                        newWeightDp=0;
                    }
                }
                else
                {
                    newWeightCount=0;
                newWeightDp=0;
                }
            }
            if (newWeightCount==1)
            {
                newWeightDp++;
                if (newWeightDp>3) //Adjust this to change the decimal places
                {
                    newWeightDp=3;
                    evt.consume();
                }
            } 
        }
        catch (NumberFormatException ex)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtNewWeightKeyTyped

    private void txtNewWeightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewWeightFocusLost
        if (txtNewWeight.getText().contains("."))
            {
                newWeightCount=1;
            }
            else
            {
                newWeightCount=0;
                newWeightDp=0;
            }
    }//GEN-LAST:event_txtNewWeightFocusLost

    private void txtEditPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditPriceKeyTyped
        try{
            Double.parseDouble(txtEditPrice.getText()+evt.getKeyChar());
            if (evt.getKeyChar()=='.')
            {
                editPriceCount=1;
            }
            if (Character.isISOControl(evt.getKeyChar()))
            {
                if (txtEditPrice.getText().contains("."))
                {
                    editPriceDp=editPriceDp-2;
                    if (editPriceDp==0)
                    {
                        editPriceDp=0;
                    }
                }
                else
                {
                    editPriceCount=0;
                editPriceDp=0;
                }
            }
            if (editPriceCount==1)
            {
                editPriceDp++;
                if (editPriceDp>3) //Adjust this to change the decimal places
                {
                    editPriceDp=3;
                    evt.consume();
                }
            } 
        }
        catch (NumberFormatException ex)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtEditPriceKeyTyped

    private void txtEditPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEditPriceFocusLost
        if (txtEditPrice.getText().contains("."))
            {
                editPriceCount=1;
            }
            else
            {
                editPriceCount=0;
                editPriceDp=0;
            }
    }//GEN-LAST:event_txtEditPriceFocusLost

    private void txtEditWeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditWeightKeyTyped
        try{
            Double.parseDouble(txtEditWeight.getText()+evt.getKeyChar());
            if (evt.getKeyChar()=='.')
            {
                editWeightCount=1;
            }
            if (Character.isISOControl(evt.getKeyChar()))
            {
                if (txtEditWeight.getText().contains("."))
                {
                    editWeightDp=editWeightDp-2;
                    if (editWeightDp==0)
                    {
                        editWeightDp=0;
                    }
                }
                else
                {
                    editWeightCount=0;
                editWeightDp=0;
                }
            }
            if (editWeightCount==1)
            {
                editWeightDp++;
                if (editWeightDp>3) //Adjust this to change the decimal places
                {
                    editWeightDp=3;
                    evt.consume();
                }
            } 
        }
        catch (NumberFormatException ex)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtEditWeightKeyTyped

    private void txtEditWeightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEditWeightFocusLost
        if (txtEditWeight.getText().contains("."))
            {
                editWeightCount=1;
            }
            else
            {
                editWeightCount=0;
                editWeightDp=0;
            }
    }//GEN-LAST:event_txtEditWeightFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Product_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Product_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Product_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Product_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Product_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewAddCategory;
    private javax.swing.JButton btnOrderItemMenu;
    private javax.swing.JButton btnOrderMenu;
    private javax.swing.JButton btnProductMenu;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUserMenu;
    private javax.swing.JButton btnView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cboNewCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPConfirmPassword;
    private javax.swing.JLabel lblPConfirmPassword1;
    private javax.swing.JLabel lblPConfirmPassword3;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRole1;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel lblUsername2;
    private javax.swing.JLabel lblUsername3;
    private javax.swing.JLabel lblUsername5;
    private javax.swing.JLabel lblUsername6;
    private javax.swing.JList<String> lstView;
    private javax.swing.JRadioButton rdoEditFragile;
    private javax.swing.JRadioButton rdoEditName;
    private javax.swing.JRadioButton rdoEditNonFragile;
    private javax.swing.JRadioButton rdoEditPrice;
    private javax.swing.JRadioButton rdoEditQuantity;
    private javax.swing.JRadioButton rdoEditType;
    private javax.swing.JRadioButton rdoEditWeight;
    private javax.swing.JRadioButton rdoNewFragile;
    private javax.swing.JRadioButton rdoNewNonFragile;
    private javax.swing.JRadioButton rdoViewFragile;
    private javax.swing.JRadioButton rdoViewNonFragile;
    private javax.swing.JTextField txtEditName;
    private javax.swing.JTextField txtEditPrice;
    private javax.swing.JTextField txtEditQuantity;
    private javax.swing.JTextField txtEditWeight;
    private javax.swing.JTextField txtNewCategory;
    private javax.swing.JTextField txtNewName;
    private javax.swing.JTextField txtNewPrice;
    private javax.swing.JTextField txtNewQuantity;
    private javax.swing.JTextField txtNewWeight;
    private javax.swing.JTextField txtSearchProduct;
    // End of variables declaration//GEN-END:variables
}
